// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CardPopular: typeof import('./src/components/CardPopular.vue')['default']
    TestmonialSec: typeof import('./src/components/TestmonialSec.vue')['default']
  }
}
